server:
  port: 9090


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://@${eureka.instance.hostname}:${server.port}/eureka/

  server:
    enable-self-preservation: true

spring:
  application:
    name: server