#spring.application.name=config-server
#server.port=8888
#
#spring.cloud.config.server.git.uri=https://github.com/forezp/SpringcloudConfig/
#spring.cloud.config.server.git.searchPaths=respo
#spring.cloud.config.label=master
#spring.cloud.config.server.git.username=
#spring.cloud.config.server.git.password=

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wjxinluoshan/spring-cloud-config
      label: master
  application:
    name: config-server
server:
  port: 8050

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
  instance:
    appname: config-server
